---
agent_info:
  agent_name: 'ppo_agent'
  version: "v0"
  load_path: null #Path of previous agent save file, if starting from previously trained agent

env_info:
  env_name: 'single_mallet_alternating_v0'

test_info:
  #Overrides individual render modes for validation tests. Set as 'None' to use mode in individual configs
  render_mode: "rgb_array" 
  test_names: 
    - "basic_defence_val_test_v0"
    - "basic_offence_val_test_v0"
