---
agent_info:
  agent_name: 'x_entropy_agent'
  version: "v0"
  load_path: null #Path of previous agent save file, if starting from previously trained agent

env_info:
  env_name: 'single_mallet_blocking_discrete_v1'
