---
# Config file for Advanced Offence Test V0

class_name: "AdvOffenceValTest"

test_params: 
  render_mode: "human" #Options are 'human', 'rgb_array', 'depth_array'
  discrete_actions: True
  data_name: "adv_off_test_data_100_eps_01-27-20-53.pkl"
#Data options:
# - adv_off_test_data_100_eps_01-27-20-53.pkl - Basic dataset with 100 randomized puck position ICs. Agent mallet
#   spawns in front of its goal and opponent mallet spawns in corner.
