---
# Config file for Basic Defence Test V0

class_name: "BasicOffenceValTest"

test_params: 
  render_mode: "human" #Options are 'human', 'rgb_array', 'depth_array'
  discrete_actions: True
  accel_mag: 1.0
