---
class_name: 'SingleMalletShootEnvV2'

init_params:
  max_reward: 1
  render_mode: "rgb_array" #Options are 'human', 'rgb_array', 'depth_array'
  puck_box:
  - [-0.5, 0]
  - [-0.5, 0]
  mal1_box: 
  - [-0.9, 0]
  - [-0.9, 0]
  mal2_box:
  - [0.05, 0.45]
  - [0.95,-0.45]
  max_accel: 5
  discrete_actions: True
